"""add_personas_posts_relationships

Revision ID: 371048119e7a
Revises: 49174858a901
Create Date: 2026-03-18 10:19:32.184716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '371048119e7a'
down_revision: Union[str, Sequence[str], None] = '49174858a901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(length=280), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('author_type', sa.String(length=10), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('post_type', sa.String(length=10), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('reply_count', sa.Integer(), nullable=True),
    sa.Column('quote_count', sa.Integer(), nullable=True),
    sa.Column('viral_score', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_posts_author_id'), 'posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_posts_created_at'), 'posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_posts_parent_id'), 'posts', ['parent_id'], unique=False)
    op.create_index(op.f('ix_posts_viral_score'), 'posts', ['viral_score'], unique=False)
    op.create_table('ai_personas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bio', sa.String(length=300), nullable=True),
    sa.Column('personality', sa.String(length=300), nullable=False),
    sa.Column('language_style', sa.String(length=50), nullable=False),
    sa.Column('slang_level', sa.String(length=10), nullable=True),
    sa.Column('catchphrases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('use_emojis', sa.Boolean(), nullable=True),
    sa.Column('posting_freq_minutes', sa.Integer(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('daily_posts_today', sa.Integer(), nullable=True),
    sa.Column('daily_calls_today', sa.Integer(), nullable=True),
    sa.Column('last_post_at', sa.DateTime(), nullable=True),
    sa.Column('mood_today', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('persona_a_id', sa.UUID(), nullable=False),
    sa.Column('persona_b_id', sa.UUID(), nullable=False),
    sa.Column('score_a_to_b', sa.Integer(), nullable=True),
    sa.Column('score_b_to_a', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('last_interaction_at', sa.DateTime(), nullable=True),
    sa.Column('cooldown_until', sa.DateTime(), nullable=True),
    sa.Column('inside_jokes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['persona_a_id'], ['ai_personas.id'], ),
    sa.ForeignKeyConstraint(['persona_b_id'], ['ai_personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_persona_a_id'), 'relationships', ['persona_a_id'], unique=False)
    op.create_index(op.f('ix_relationships_persona_b_id'), 'relationships', ['persona_b_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationships_persona_b_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_persona_a_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_table('ai_personas')
    op.drop_index(op.f('ix_posts_viral_score'), table_name='posts')
    op.drop_index(op.f('ix_posts_parent_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_author_id'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
