"""update_relationship_persistent_memory

Revision ID: 769a45449b5f
Revises: 343d287729c1
Create Date: 2026-03-20 16:56:44.026207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '769a45449b5f'
down_revision: Union[str, Sequence[str], None] = '343d287729c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('persona_id', sa.UUID(), nullable=False))
    op.add_column('relationships', sa.Column('target_id', sa.UUID(), nullable=False))
    op.add_column('relationships', sa.Column('target_type', sa.String(length=10), nullable=False))
    op.add_column('relationships', sa.Column('target_name', sa.String(length=100), nullable=True))
    op.add_column('relationships', sa.Column('score', sa.Integer(), nullable=True))
    op.add_column('relationships', sa.Column('roast_count', sa.Integer(), nullable=True))
    op.add_column('relationships', sa.Column('interaction_count', sa.Integer(), nullable=True))
    op.alter_column('relationships', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.drop_index(op.f('ix_relationships_persona_a_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_persona_b_id'), table_name='relationships')
    op.create_index(op.f('ix_relationships_persona_id'), 'relationships', ['persona_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_id'), 'relationships', ['target_id'], unique=False)
    op.drop_constraint(op.f('relationships_persona_b_id_fkey'), 'relationships', type_='foreignkey')
    op.drop_constraint(op.f('relationships_persona_a_id_fkey'), 'relationships', type_='foreignkey')
    op.create_foreign_key(None, 'relationships', 'ai_personas', ['persona_id'], ['id'])
    op.drop_column('relationships', 'score_b_to_a')
    op.drop_column('relationships', 'score_a_to_b')
    op.drop_column('relationships', 'cooldown_until')
    op.drop_column('relationships', 'inside_jokes')
    op.drop_column('relationships', 'persona_a_id')
    op.drop_column('relationships', 'persona_b_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('persona_b_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('relationships', sa.Column('persona_a_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('relationships', sa.Column('inside_jokes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('relationships', sa.Column('cooldown_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('relationships', sa.Column('score_a_to_b', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('relationships', sa.Column('score_b_to_a', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.create_foreign_key(op.f('relationships_persona_a_id_fkey'), 'relationships', 'ai_personas', ['persona_a_id'], ['id'])
    op.create_foreign_key(op.f('relationships_persona_b_id_fkey'), 'relationships', 'ai_personas', ['persona_b_id'], ['id'])
    op.drop_index(op.f('ix_relationships_target_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_persona_id'), table_name='relationships')
    op.create_index(op.f('ix_relationships_persona_b_id'), 'relationships', ['persona_b_id'], unique=False)
    op.create_index(op.f('ix_relationships_persona_a_id'), 'relationships', ['persona_a_id'], unique=False)
    op.alter_column('relationships', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('relationships', 'interaction_count')
    op.drop_column('relationships', 'roast_count')
    op.drop_column('relationships', 'score')
    op.drop_column('relationships', 'target_name')
    op.drop_column('relationships', 'target_type')
    op.drop_column('relationships', 'target_id')
    op.drop_column('relationships', 'persona_id')
    # ### end Alembic commands ###
