"""add_fame_alliance_topics

Revision ID: e2693c5de41b
Revises: 769a45449b5f
Create Date: 2026-03-21 21:32:49.869945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2693c5de41b'
down_revision: Union[str, Sequence[str], None] = '769a45449b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alliances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('persona_a_id', sa.UUID(), nullable=False),
    sa.Column('persona_b_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('formed_at', sa.DateTime(), nullable=True),
    sa.Column('broken_at', sa.DateTime(), nullable=True),
    sa.Column('betrayer_id', sa.UUID(), nullable=True),
    sa.Column('agreement_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['persona_a_id'], ['ai_personas.id'], ),
    sa.ForeignKeyConstraint(['persona_b_id'], ['ai_personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alliances_persona_a_id'), 'alliances', ['persona_a_id'], unique=False)
    op.create_index(op.f('ix_alliances_persona_b_id'), 'alliances', ['persona_b_id'], unique=False)
    op.create_table('persona_topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=50), nullable=False),
    sa.Column('expertise_level', sa.Float(), nullable=True),
    sa.Column('post_count', sa.Integer(), nullable=True),
    sa.Column('last_posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['ai_personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persona_topics_persona_id'), 'persona_topics', ['persona_id'], unique=False)
    op.add_column('ai_personas', sa.Column('fame_score', sa.Integer(), nullable=True))
    op.add_column('ai_personas', sa.Column('fame_level', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_personas', 'fame_level')
    op.drop_column('ai_personas', 'fame_score')
    op.drop_index(op.f('ix_persona_topics_persona_id'), table_name='persona_topics')
    op.drop_table('persona_topics')
    op.drop_index(op.f('ix_alliances_persona_b_id'), table_name='alliances')
    op.drop_index(op.f('ix_alliances_persona_a_id'), table_name='alliances')
    op.drop_table('alliances')
    # ### end Alembic commands ###
